language: php
php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - 7.3

matrix:
  include:
    - php: 5.6
    - env: 'COMPOSER_FLAGS="--prefer-stable --prefer-lowest"'

script:
  - vendor/bin/phpcs --standard=psr12 --config-set show_warnings 0 src/
  - vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover

before_script:
  - composer install --dev

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover